name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.7
    - run: gcc --version
    - run: conda --version
    - run: which python
    - name: Run installation.
      run: |
        conda install -c pytorch -c pyg -c conda-forge scipy pyg pytorch=1.10
        pip install codecov
        pip install sphinx sphinx_rtd_theme
        pip install .[test]
        python setup.py install
    - name: Test coverage.
      run: |
        python setup.py test